pipeline {
    agent any
    options {
      ansiColor('gnome-terminal')
    }
    stages {
         stage('Run python script'){
        steps{
            git url:'https://github.com/MatthewJDavis/python.git'
            sh 'python3 jenkins-python-example/hello.py'
        }
    }   
    }
}