pipeline {
    agent any
    options {
      ansiColor('gnome-terminal')
    }
    stages {
      stage('Clean out workspace'){
        steps{
          sh 'pwd'
          sh 'ls -l'
          sh 'rm -rf *'
          sh 'ls -l'
        }
      }
      stage('Checkout from git') {
        steps {
          git url:'https://github.com/MatthewJDavis/python.git'
        }
      }
      stage('Run python script') {
        steps {
          sh 'python3 jenkins-python-example/hello.py'
        }
      }
    }   
}