pipeline {
    agent any
    options {
      ansiColor('gnome-terminal')
    }
    stages {
        stage('Checkout from git') {
          step {
            sh 'python3 jenkins-python-example/hello.py'
          }
        }
        stage('Run python script') {
            step {
              sh 'python3 jenkins-python-example/hello.py'
            }
        }
    }   
}