---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7.6-slim-buster
inputs:
- name: source-code
run:
  path: sh
  args:
  - -exec
  - |
    pip install pylint
    pylint ./source-code/dns/resolve.py