---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/MatthewJDavis/python.git
    branch: master

jobs:
- name: run-system-info
  plan:
  - get: source-code
    trigger: true
  - task: pwd
    file: source-code/system-info/ci/tasks/pwd.yml
  - task: output-repo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.7.6-slim-buster
      inputs:
      - name: source-code
      run:
        path: find
        args: [.]
  - task: run-system-info-program
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.7.6-slim-buster
      inputs:
      - name: source-code
      run:
        path: sh
        args:
        - -exec
        - |
          python ./source-code/system-info/system_info.py