---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7.6-slim-buster
inputs:
- name: source-code
run:
  path: sh
  args:
  - -exec
  - |
    python ./source-code/system-info/system_info.py